namespace Bost.Proto.Enum
{
	public enum StatusTable
	{
		Arrow = 0,
		RabbitMinecartSpawner = 1,
		LivingEntity = 2,
		SnowballThrownEggLivingEntity = 3,
		IronGolemEvokerFangsRavager = 4,
		None,
		AbstractHorseTameableAnimal1,
		AbstractHorseTameableAnimal2,
		Wolf,
		Player,
		SheepMinecartTNT,
		IronGolem,
		Villager1,
		Villager2,
		Villager3,
		Witch,
		ZombieVillager,
		FireworkRocketEntity,
		Animal,
		Squid,
		Mob,
		Guardian,
		Player1,
		Player2,
		Player3,
		Player4,
		Player5,
		Player6,
		Player7,
		LivingEntity1,
		LivingEntity2,
		FishingHook,
		ArmorStand,
		LivingEntity3,
		IronGolem2,
		LivingEntity4,
		LivingEntity5,
		LivingEntity6,
		Dolphin,
		Ravager,
		Ocelot,
		Ocelot2,
		Villager,
		Player8,
		LivingEntity7,
		Fox,
		LivingEntity8,
		LivingEntity9,
		LivingEntity10,
		LivingEntity11,
		LivingEntity12,
		LivingEntity13,
		LivingEntity14,
		Entity,
		LivingEntity15,
		LivingEntit16
	}
}
